# Generated by Django 4.2.7 on 2024-09-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_orderitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
