# Generated by Django 4.2.7 on 2024-09-18 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
