# Generated by Django 4.2.7 on 2024-09-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_remove_orderitem_price_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
